Mon, 25 Feb 2019 11:04:54 INFO hebei.py:23[<module>()] Hebei starts
Mon, 25 Feb 2019 11:04:54 INFO yzftaxbot.py:578[register_login_task()] 
Mon, 25 Feb 2019 11:04:54 INFO yzftaxbot.py:618[run()] 第1次运行登录函数
Mon, 25 Feb 2019 11:05:15 ERROR hebei.py:29[<module>()] 不支持任务type:SB
Traceback (most recent call last):
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 25, in <module>
    main()
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 18, in main
    MyBot.run()
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 632, in run
    raise Exception("不支持任务type:" + task_group.type())
Exception: 不支持任务type:SB
Mon, 25 Feb 2019 11:20:20 INFO hebei.py:23[<module>()] Hebei starts
Mon, 25 Feb 2019 11:20:21 INFO yzftaxbot.py:578[register_login_task()] 
Mon, 25 Feb 2019 11:20:22 INFO yzftaxbot.py:618[run()] 第1次运行登录函数
Mon, 25 Feb 2019 11:23:17 INFO hebei.py:23[<module>()] Hebei starts
Mon, 25 Feb 2019 11:23:18 INFO yzftaxbot.py:578[register_login_task()] 
Mon, 25 Feb 2019 11:23:19 INFO yzftaxbot.py:618[run()] 第1次运行登录函数
Mon, 25 Feb 2019 11:23:35 INFO yzftaxbot.py:642[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Mon, 25 Feb 2019 11:23:52 ERROR yzftaxbot.py:648[run()] Message: no such element: Unable to locate element: {"method":"id","selector":"mine-ul > li:nth-child(1)"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 645, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 11, in main
    YzfBrowser.find_element_by_id("mine-ul > li:nth-child(1)").click()
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"mine-ul > li:nth-child(1)"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Mon, 25 Feb 2019 11:23:56 ERROR hebei.py:29[<module>()] Message: no such element: Unable to locate element: {"method":"id","selector":"mine-ul > li:nth-child(1)"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 25, in <module>
    main()
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 18, in main
    MyBot.run()
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 650, in run
    raise e  # TODO 重试次数用完，设置Task
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 645, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 11, in main
    YzfBrowser.find_element_by_id("mine-ul > li:nth-child(1)").click()
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"mine-ul > li:nth-child(1)"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Mon, 25 Feb 2019 14:29:57 INFO hebei.py:23[<module>()] Hebei starts
Mon, 25 Feb 2019 14:29:57 INFO yzftaxbot.py:578[register_login_task()] 
Mon, 25 Feb 2019 14:30:07 INFO yzftaxbot.py:618[run()] 第1次运行登录函数
Mon, 25 Feb 2019 14:30:23 INFO yzftaxbot.py:642[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Mon, 25 Feb 2019 14:33:29 INFO hebei.py:23[<module>()] Hebei starts
Mon, 25 Feb 2019 14:33:29 INFO yzftaxbot.py:578[register_login_task()] 
Mon, 25 Feb 2019 14:33:29 INFO yzftaxbot.py:618[run()] 第1次运行登录函数
Mon, 25 Feb 2019 14:33:36 INFO yzftaxbot.py:642[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Mon, 25 Feb 2019 14:35:10 INFO hebei.py:23[<module>()] Hebei starts
Mon, 25 Feb 2019 14:35:10 INFO yzftaxbot.py:578[register_login_task()] 
Mon, 25 Feb 2019 14:35:10 INFO yzftaxbot.py:618[run()] 第1次运行登录函数
Mon, 25 Feb 2019 14:35:18 INFO yzftaxbot.py:642[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Mon, 25 Feb 2019 14:36:43 INFO hebei.py:23[<module>()] Hebei starts
Mon, 25 Feb 2019 14:36:43 INFO yzftaxbot.py:578[register_login_task()] 
Mon, 25 Feb 2019 14:36:43 INFO yzftaxbot.py:618[run()] 第1次运行登录函数
Mon, 25 Feb 2019 14:36:51 INFO yzftaxbot.py:642[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Mon, 25 Feb 2019 15:11:29 INFO hebei.py:23[<module>()] Hebei starts
Mon, 25 Feb 2019 15:11:29 INFO yzftaxbot.py:578[register_login_task()] 
Mon, 25 Feb 2019 15:11:29 INFO yzftaxbot.py:618[run()] 第1次运行登录函数
Tue, 26 Feb 2019 10:01:36 INFO hebei.py:23[<module>()] Hebei starts
Tue, 26 Feb 2019 10:01:36 INFO yzftaxbot.py:578[register_login_task()] 
Tue, 26 Feb 2019 10:01:36 INFO yzftaxbot.py:618[run()] 第1次运行登录函数
Tue, 26 Feb 2019 10:02:01 INFO hebei.py:23[<module>()] Hebei starts
Tue, 26 Feb 2019 10:02:01 INFO yzftaxbot.py:578[register_login_task()] 
Tue, 26 Feb 2019 10:02:01 INFO yzftaxbot.py:618[run()] 第1次运行登录函数
Tue, 26 Feb 2019 10:02:09 INFO yzftaxbot.py:642[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 10:08:45 INFO hebei.py:23[<module>()] Hebei starts
Tue, 26 Feb 2019 10:08:45 INFO yzftaxbot.py:578[register_login_task()] 
Tue, 26 Feb 2019 10:08:45 INFO yzftaxbot.py:618[run()] 第1次运行登录函数
Tue, 26 Feb 2019 10:08:54 INFO yzftaxbot.py:642[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 10:09:16 ERROR yzftaxbot.py:648[run()] Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 645, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 19, in main
    YzfTbody = read_tbody("// *[ @ id = 'app'] / div / div / section / div / section / div / div / div[2] / span / div[2] / div / div / div / div / table", "tr", "td")
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 768, in read_tbody
    frame_id_list_list = analyze_element_frames(tbody_selector_str)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 693, in analyze_element_frames
    _analyze_element_frames(element_css_selector, frame_id_list_list)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 687, in _analyze_element_frames
    __analyze_element_frames(element_css_selector, tmp_frame_id_list, frame_id_list_list)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 668, in __analyze_element_frames
    elements = YzfBrowser.find_elements_by_css_selector(ele_sel)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 614, in find_elements_by_css_selector
    return self.find_elements(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1007, in find_elements
    'value': value})['value'] or []
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 10:09:19 ERROR hebei.py:29[<module>()] Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 25, in <module>
    main()
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 18, in main
    MyBot.run()
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 650, in run
    raise e  # TODO 重试次数用完，设置Task
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 645, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 19, in main
    YzfTbody = read_tbody("// *[ @ id = 'app'] / div / div / section / div / section / div / div / div[2] / span / div[2] / div / div / div / div / table", "tr", "td")
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 768, in read_tbody
    frame_id_list_list = analyze_element_frames(tbody_selector_str)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 693, in analyze_element_frames
    _analyze_element_frames(element_css_selector, frame_id_list_list)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 687, in _analyze_element_frames
    __analyze_element_frames(element_css_selector, tmp_frame_id_list, frame_id_list_list)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 668, in __analyze_element_frames
    elements = YzfBrowser.find_elements_by_css_selector(ele_sel)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 614, in find_elements_by_css_selector
    return self.find_elements(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1007, in find_elements
    'value': value})['value'] or []
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 10:09:20 INFO yzfbrowser.py:18[Quit()] Quit() exit browser
Tue, 26 Feb 2019 10:15:20 INFO hebei.py:23[<module>()] Hebei starts
Tue, 26 Feb 2019 10:15:20 INFO yzftaxbot.py:578[register_login_task()] 
Tue, 26 Feb 2019 10:15:20 INFO yzftaxbot.py:618[run()] 第1次运行登录函数
Tue, 26 Feb 2019 10:15:28 INFO yzftaxbot.py:642[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 10:24:26 INFO hebei.py:23[<module>()] Hebei starts
Tue, 26 Feb 2019 10:24:26 INFO yzftaxbot.py:578[register_login_task()] 
Tue, 26 Feb 2019 10:24:26 INFO yzftaxbot.py:618[run()] 第1次运行登录函数
Tue, 26 Feb 2019 10:24:34 INFO yzftaxbot.py:642[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 10:24:40 ERROR yzftaxbot.py:648[run()] Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (285, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 645, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 15, in main
    YzfBrowser.find_element_by_xpath("//*[@id='app']/div/div/section/div/section/div/div/div[1]/div[2]/div/div/div/div[3]/div").click()
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (285, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 10:24:40 ERROR hebei.py:29[<module>()] Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (285, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 25, in <module>
    main()
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 18, in main
    MyBot.run()
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 650, in run
    raise e  # TODO 重试次数用完，设置Task
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 645, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 15, in main
    YzfBrowser.find_element_by_xpath("//*[@id='app']/div/div/section/div/section/div/div/div[1]/div[2]/div/div/div/div[3]/div").click()
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (285, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 10:24:40 INFO yzfbrowser.py:18[Quit()] Quit() exit browser
Tue, 26 Feb 2019 10:25:28 INFO hebei.py:23[<module>()] Hebei starts
Tue, 26 Feb 2019 10:25:28 INFO yzftaxbot.py:578[register_login_task()] 
Tue, 26 Feb 2019 10:25:28 INFO yzftaxbot.py:618[run()] 第1次运行登录函数
Tue, 26 Feb 2019 10:25:36 INFO yzftaxbot.py:642[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 10:25:42 ERROR yzftaxbot.py:648[run()] Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (285, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 645, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 15, in main
    YzfBrowser.find_element_by_xpath("//*[@id='app']/div/div/section/div/section/div/div/div[1]/div[2]/div/div/div/div[3]/div").click()
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (285, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 10:25:42 ERROR hebei.py:29[<module>()] Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (285, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 25, in <module>
    main()
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 18, in main
    MyBot.run()
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 650, in run
    raise e  # TODO 重试次数用完，设置Task
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 645, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 15, in main
    YzfBrowser.find_element_by_xpath("//*[@id='app']/div/div/section/div/section/div/div/div[1]/div[2]/div/div/div/div[3]/div").click()
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (285, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 10:25:42 INFO yzfbrowser.py:18[Quit()] Quit() exit browser
Tue, 26 Feb 2019 11:24:09 INFO hebei.py:23[<module>()] Hebei starts
Tue, 26 Feb 2019 11:24:09 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 11:24:09 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 11:24:15 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 11:30:31 ERROR yzftaxbot.py:725[run()] Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 722, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 20, in main
    table = read_tbody("// *[ @ id = 'app'] / div / div / section / div / section / div / div / div[2] / span / div[2] / div / div / div / div / table /tbody", "tr", "td")
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 845, in read_tbody
    frame_id_list_list = analyze_element_frames(tbody_selector_str)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 770, in analyze_element_frames
    _analyze_element_frames(element_css_selector, frame_id_list_list)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 764, in _analyze_element_frames
    __analyze_element_frames(element_css_selector, tmp_frame_id_list, frame_id_list_list)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 745, in __analyze_element_frames
    elements = YzfBrowser.find_elements_by_css_selector(ele_sel)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 614, in find_elements_by_css_selector
    return self.find_elements(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1007, in find_elements
    'value': value})['value'] or []
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 11:31:57 INFO hebei.py:23[<module>()] Hebei starts
Tue, 26 Feb 2019 11:31:57 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 11:31:57 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 11:32:06 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 11:32:21 ERROR yzftaxbot.py:725[run()] Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 722, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 20, in main
    table = read_tbody("//*[@id='app']/div/div/section/div/section/div/div/div[2]/span/div[2]/div/div/div/div/table/tbody", "tr", "td")
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 845, in read_tbody
    frame_id_list_list = analyze_element_frames(tbody_selector_str)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 770, in analyze_element_frames
    _analyze_element_frames(element_css_selector, frame_id_list_list)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 764, in _analyze_element_frames
    __analyze_element_frames(element_css_selector, tmp_frame_id_list, frame_id_list_list)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 745, in __analyze_element_frames
    elements = YzfBrowser.find_elements_by_css_selector(ele_sel)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 614, in find_elements_by_css_selector
    return self.find_elements(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1007, in find_elements
    'value': value})['value'] or []
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 11:32:27 ERROR hebei.py:29[<module>()] Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 25, in <module>
    main()
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 18, in main
    MyBot.run()
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 727, in run
    raise e  # TODO 重试次数用完，设置Task
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 722, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 20, in main
    table = read_tbody("//*[@id='app']/div/div/section/div/section/div/div/div[2]/span/div[2]/div/div/div/div/table/tbody", "tr", "td")
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 845, in read_tbody
    frame_id_list_list = analyze_element_frames(tbody_selector_str)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 770, in analyze_element_frames
    _analyze_element_frames(element_css_selector, frame_id_list_list)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 764, in _analyze_element_frames
    __analyze_element_frames(element_css_selector, tmp_frame_id_list, frame_id_list_list)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 745, in __analyze_element_frames
    elements = YzfBrowser.find_elements_by_css_selector(ele_sel)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 614, in find_elements_by_css_selector
    return self.find_elements(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1007, in find_elements
    'value': value})['value'] or []
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 11:36:27 INFO hebei.py:23[<module>()] Hebei starts
Tue, 26 Feb 2019 11:36:27 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 11:36:27 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 11:36:35 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 11:37:49 INFO hebei.py:23[<module>()] Hebei starts
Tue, 26 Feb 2019 11:37:49 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 11:37:49 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 11:37:58 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 11:42:17 INFO hebei.py:26[<module>()] Hebei exits normally
Tue, 26 Feb 2019 11:42:17 INFO yzfbrowser.py:18[Quit()] Quit() exit browser
Tue, 26 Feb 2019 11:43:10 INFO hebei.py:23[<module>()] Hebei starts
Tue, 26 Feb 2019 11:43:10 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 11:43:10 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 11:43:20 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 11:43:44 INFO hebei.py:26[<module>()] Hebei exits normally
Tue, 26 Feb 2019 11:43:45 INFO yzfbrowser.py:18[Quit()] Quit() exit browser
Tue, 26 Feb 2019 11:44:34 INFO hebei.py:23[<module>()] Hebei starts
Tue, 26 Feb 2019 11:44:34 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 11:44:34 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 11:44:47 ERROR yzftaxbot.py:701[run()] 'NoneType' object has no attribute 'is_displayed'
Traceback (most recent call last):
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 697, in run
    self.LoginTaskFunc()
  File "D:\InterfaceSystem\RPA\hebei\tasks\login.py", line 49, in main
    WebDriverWait(YzfBrowser, 30).until(EC.element_to_be_clickable((By.ID, "companyEnter")))
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 297, in __call__
    element = visibility_of_element_located(self.locator)(driver)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 148, in _element_if_visible
    return element if element.is_displayed() == visibility else False
AttributeError: 'NoneType' object has no attribute 'is_displayed'
Tue, 26 Feb 2019 11:44:48 ERROR hebei.py:29[<module>()] 'NoneType' object has no attribute 'is_displayed'
Traceback (most recent call last):
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 25, in <module>
    main()
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 18, in main
    MyBot.run()
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 703, in run
    raise e  # 重试次数用完，向外层抛异常
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 697, in run
    self.LoginTaskFunc()
  File "D:\InterfaceSystem\RPA\hebei\tasks\login.py", line 49, in main
    WebDriverWait(YzfBrowser, 30).until(EC.element_to_be_clickable((By.ID, "companyEnter")))
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 297, in __call__
    element = visibility_of_element_located(self.locator)(driver)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 148, in _element_if_visible
    return element if element.is_displayed() == visibility else False
AttributeError: 'NoneType' object has no attribute 'is_displayed'
Tue, 26 Feb 2019 11:44:48 INFO yzfbrowser.py:18[Quit()] Quit() exit browser
Tue, 26 Feb 2019 11:44:54 INFO hebei.py:23[<module>()] Hebei starts
Tue, 26 Feb 2019 11:44:54 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 11:44:54 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 11:45:02 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 11:45:07 ERROR yzftaxbot.py:725[run()] Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (285, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 722, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 15, in main
    YzfBrowser.find_element_by_xpath("//*[@id='app']/div/div/section/div/section/div/div/div[1]/div[2]/div/div/div/div[3]/div").click()
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (285, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 11:45:07 ERROR hebei.py:29[<module>()] Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (285, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 25, in <module>
    main()
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 18, in main
    MyBot.run()
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 727, in run
    raise e  # TODO 重试次数用完，设置Task
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 722, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 15, in main
    YzfBrowser.find_element_by_xpath("//*[@id='app']/div/div/section/div/section/div/div/div[1]/div[2]/div/div/div/div[3]/div").click()
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (285, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 11:45:07 INFO yzfbrowser.py:18[Quit()] Quit() exit browser
Tue, 26 Feb 2019 11:45:20 INFO hebei.py:23[<module>()] Hebei starts
Tue, 26 Feb 2019 11:45:20 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 11:45:20 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 11:45:28 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 13:43:41 INFO hebei.py:23[<module>()] Hebei starts
Tue, 26 Feb 2019 13:43:41 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 13:43:41 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 13:43:51 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 13:43:58 ERROR yzftaxbot.py:725[run()] Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (285, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 722, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 15, in main
    YzfBrowser.find_element_by_xpath("//*[@id='app']/div/div/section/div/section/div/div/div[1]/div[2]/div/div/div/div[3]/div").click()
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (285, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 13:43:58 ERROR hebei.py:29[<module>()] Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (285, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 25, in <module>
    main()
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 18, in main
    MyBot.run()
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 727, in run
    raise e  # TODO 重试次数用完，设置Task
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 722, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 15, in main
    YzfBrowser.find_element_by_xpath("//*[@id='app']/div/div/section/div/section/div/div/div[1]/div[2]/div/div/div/div[3]/div").click()
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (285, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 13:43:58 INFO yzfbrowser.py:18[Quit()] Quit() exit browser
Tue, 26 Feb 2019 13:44:28 INFO hebei.py:23[<module>()] Hebei starts
Tue, 26 Feb 2019 13:44:28 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 13:44:28 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 13:44:36 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 13:46:12 INFO hebei.py:23[<module>()] Hebei starts
Tue, 26 Feb 2019 13:46:12 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 13:46:12 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 13:46:22 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 13:46:29 ERROR yzftaxbot.py:725[run()] Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (485, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 722, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 15, in main
    YzfBrowser.find_element_by_xpath("//*[@id='app']/div/div/section/div/section/div/div/div[1]/div[2]/div/div/div/div[3]/div").click()
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (485, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 13:46:29 ERROR hebei.py:29[<module>()] Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (485, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 25, in <module>
    main()
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 18, in main
    MyBot.run()
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 727, in run
    raise e  # TODO 重试次数用完，设置Task
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 722, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 15, in main
    YzfBrowser.find_element_by_xpath("//*[@id='app']/div/div/section/div/section/div/div/div[1]/div[2]/div/div/div/div[3]/div").click()
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (485, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 13:46:29 INFO yzfbrowser.py:18[Quit()] Quit() exit browser
Tue, 26 Feb 2019 13:46:40 INFO hebei.py:23[<module>()] Hebei starts
Tue, 26 Feb 2019 13:46:40 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 13:46:40 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 13:46:49 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 15:34:55 INFO hebei.py:25[<module>()] Hebei starts
Tue, 26 Feb 2019 15:35:51 INFO hebei.py:24[<module>()] Hebei starts
Tue, 26 Feb 2019 15:35:51 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 15:35:51 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 15:36:01 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 15:37:10 INFO hebei.py:24[<module>()] Hebei starts
Tue, 26 Feb 2019 15:37:10 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 15:37:10 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 15:37:19 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 15:37:26 ERROR yzftaxbot.py:725[run()] Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (285, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 722, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 15, in main
    YzfBrowser.find_element_by_xpath("//*[@id='app']/div/div/section/div/section/div/div/div[1]/div[2]/div/div/div/div[3]/div").click()
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (285, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 15:37:26 ERROR hebei.py:30[<module>()] Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (285, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 26, in <module>
    main()
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 19, in main
    MyBot.run()
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 727, in run
    raise e  # TODO 重试次数用完，设置Task
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 722, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 15, in main
    YzfBrowser.find_element_by_xpath("//*[@id='app']/div/div/section/div/section/div/div/div[1]/div[2]/div/div/div/div[3]/div").click()
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (285, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 15:37:26 INFO yzfbrowser.py:18[Quit()] Quit() exit browser
Tue, 26 Feb 2019 15:37:39 INFO hebei.py:24[<module>()] Hebei starts
Tue, 26 Feb 2019 15:37:39 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 15:37:39 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 15:37:47 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 15:40:10 INFO hebei.py:24[<module>()] Hebei starts
Tue, 26 Feb 2019 15:40:10 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 15:40:10 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 15:40:22 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 15:40:32 ERROR yzftaxbot.py:725[run()] Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='mine-ul']/li[2]"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 722, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 11, in main
    YzfBrowser.find_element_by_xpath("//*[@id='mine-ul']/li[2]").click()
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='mine-ul']/li[2]"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 15:40:32 ERROR hebei.py:30[<module>()] Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='mine-ul']/li[2]"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 26, in <module>
    main()
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 19, in main
    MyBot.run()
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 727, in run
    raise e  # TODO 重试次数用完，设置Task
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 722, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 11, in main
    YzfBrowser.find_element_by_xpath("//*[@id='mine-ul']/li[2]").click()
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='mine-ul']/li[2]"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 15:40:32 INFO yzfbrowser.py:18[Quit()] Quit() exit browser
Tue, 26 Feb 2019 15:40:49 INFO hebei.py:24[<module>()] Hebei starts
Tue, 26 Feb 2019 15:40:49 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 15:40:49 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 15:41:04 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 15:42:10 INFO hebei.py:24[<module>()] Hebei starts
Tue, 26 Feb 2019 15:42:10 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 15:42:10 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 15:42:17 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 15:49:44 INFO hebei.py:24[<module>()] Hebei starts
Tue, 26 Feb 2019 15:49:44 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 15:49:44 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 15:49:53 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 15:50:54 INFO hebei.py:24[<module>()] Hebei starts
Tue, 26 Feb 2019 15:50:54 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 15:50:54 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 15:51:02 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 15:52:25 INFO hebei.py:24[<module>()] Hebei starts
Tue, 26 Feb 2019 15:52:25 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 15:52:25 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 15:52:32 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 15:52:38 ERROR yzftaxbot.py:725[run()] Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (285, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 722, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 15, in main
    YzfBrowser.find_element_by_xpath("//*[@id='app']/div/div/section/div/section/div/div/div[1]/div[2]/div/div/div/div[3]/div").click()
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (285, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 15:52:38 ERROR hebei.py:30[<module>()] Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (285, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 26, in <module>
    main()
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 19, in main
    MyBot.run()
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 727, in run
    raise e  # TODO 重试次数用完，设置Task
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 722, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 15, in main
    YzfBrowser.find_element_by_xpath("//*[@id='app']/div/div/section/div/section/div/div/div[1]/div[2]/div/div/div/div[3]/div").click()
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (285, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 15:52:38 INFO yzfbrowser.py:18[Quit()] Quit() exit browser
Tue, 26 Feb 2019 15:52:47 INFO hebei.py:24[<module>()] Hebei starts
Tue, 26 Feb 2019 15:52:47 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 15:52:47 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 15:52:55 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 17:13:03 INFO hebei.py:24[<module>()] Hebei starts
Tue, 26 Feb 2019 17:13:03 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 17:13:03 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 17:13:15 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 17:13:49 ERROR yzftaxbot.py:725[run()] Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 722, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 20, in main
    tbody = read_tbody("//*[@id='app']/div/div/section/div/section/div/div/div[2]/span/div[2]/div/div/div/div/table/tbody")
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 857, in read_tbody
    frame_id_list_list = analyze_element_frames(tbody_selector_str)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 770, in analyze_element_frames
    _analyze_element_frames(element_css_selector, frame_id_list_list)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 764, in _analyze_element_frames
    __analyze_element_frames(element_css_selector, tmp_frame_id_list, frame_id_list_list)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 745, in __analyze_element_frames
    elements = YzfBrowser.find_elements_by_css_selector(ele_sel)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 614, in find_elements_by_css_selector
    return self.find_elements(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1007, in find_elements
    'value': value})['value'] or []
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 17:13:52 ERROR hebei.py:30[<module>()] Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 26, in <module>
    main()
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 19, in main
    MyBot.run()
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 727, in run
    raise e  # TODO 重试次数用完，设置Task
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 722, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 20, in main
    tbody = read_tbody("//*[@id='app']/div/div/section/div/section/div/div/div[2]/span/div[2]/div/div/div/div/table/tbody")
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 857, in read_tbody
    frame_id_list_list = analyze_element_frames(tbody_selector_str)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 770, in analyze_element_frames
    _analyze_element_frames(element_css_selector, frame_id_list_list)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 764, in _analyze_element_frames
    __analyze_element_frames(element_css_selector, tmp_frame_id_list, frame_id_list_list)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 745, in __analyze_element_frames
    elements = YzfBrowser.find_elements_by_css_selector(ele_sel)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 614, in find_elements_by_css_selector
    return self.find_elements(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1007, in find_elements
    'value': value})['value'] or []
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 17:14:19 INFO hebei.py:24[<module>()] Hebei starts
Tue, 26 Feb 2019 17:14:19 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 17:14:19 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 17:14:27 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 17:14:33 ERROR yzftaxbot.py:725[run()] Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (485, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 722, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 15, in main
    YzfBrowser.find_element_by_xpath("//*[@id='app']/div/div/section/div/section/div/div/div[1]/div[2]/div/div/div/div[3]/div").click()
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (485, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 17:14:33 ERROR hebei.py:30[<module>()] Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (485, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 26, in <module>
    main()
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 19, in main
    MyBot.run()
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 727, in run
    raise e  # TODO 重试次数用完，设置Task
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 722, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 15, in main
    YzfBrowser.find_element_by_xpath("//*[@id='app']/div/div/section/div/section/div/div/div[1]/div[2]/div/div/div/div[3]/div").click()
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <div class="ant-tabs-tab-inner" data-reactid=".0.0.0.2.0.0.0.$nav.1.2.0.0.1:$sfrd.0">...</div> is not clickable at point (485, 223). Other element would receive the click: <section class="body-loading" data-reactid=".3">...</section>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 17:14:33 INFO yzfbrowser.py:18[Quit()] Quit() exit browser
Tue, 26 Feb 2019 17:14:42 INFO hebei.py:24[<module>()] Hebei starts
Tue, 26 Feb 2019 17:14:42 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 17:14:42 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 17:14:49 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 17:17:05 INFO hebei.py:24[<module>()] Hebei starts
Tue, 26 Feb 2019 17:17:05 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 17:17:05 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 17:17:14 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 17:17:36 ERROR yzftaxbot.py:725[run()] Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 722, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 20, in main
    tbody = read_tbody("//*[@id='app']/div/div/section/div/section/div/div/div[2]/span/div[2]/div/div/div/div/table/tbody", 'tr', 'th')
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 857, in read_tbody
    frame_id_list_list = analyze_element_frames(tbody_selector_str)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 770, in analyze_element_frames
    _analyze_element_frames(element_css_selector, frame_id_list_list)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 764, in _analyze_element_frames
    __analyze_element_frames(element_css_selector, tmp_frame_id_list, frame_id_list_list)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 745, in __analyze_element_frames
    elements = YzfBrowser.find_elements_by_css_selector(ele_sel)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 614, in find_elements_by_css_selector
    return self.find_elements(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1007, in find_elements
    'value': value})['value'] or []
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 17:18:00 INFO hebei.py:24[<module>()] Hebei starts
Tue, 26 Feb 2019 17:18:00 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 17:18:00 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 17:18:11 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 17:20:51 INFO hebei.py:24[<module>()] Hebei starts
Tue, 26 Feb 2019 17:20:51 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 17:20:51 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 17:21:02 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 17:24:07 INFO hebei.py:24[<module>()] Hebei starts
Tue, 26 Feb 2019 17:24:07 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 17:24:07 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 17:24:20 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 17:28:43 INFO hebei.py:24[<module>()] Hebei starts
Tue, 26 Feb 2019 17:28:43 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 17:28:43 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 17:28:52 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 17:32:00 ERROR yzftaxbot.py:725[run()] Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 722, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 20, in main
    tbody = read_tbody("//*[@id='app']/div/div/section/div/section/div/div/div[2]/span/div[2]/div/div/div/div/table/tbody", 'tr', 'td')
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 857, in read_tbody
    frame_id_list_list = analyze_element_frames(tbody_selector_str)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 770, in analyze_element_frames
    _analyze_element_frames(element_css_selector, frame_id_list_list)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 764, in _analyze_element_frames
    __analyze_element_frames(element_css_selector, tmp_frame_id_list, frame_id_list_list)
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 745, in __analyze_element_frames
    elements = YzfBrowser.find_elements_by_css_selector(ele_sel)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 614, in find_elements_by_css_selector
    return self.find_elements(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1007, in find_elements
    'value': value})['value'] or []
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 17:32:29 INFO hebei.py:24[<module>()] Hebei starts
Tue, 26 Feb 2019 17:32:29 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 17:32:29 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 17:32:38 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 17:35:27 INFO hebei.py:24[<module>()] Hebei starts
Tue, 26 Feb 2019 17:35:27 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 17:35:27 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 17:35:37 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 17:39:50 INFO hebei.py:27[<module>()] Hebei exits normally
Tue, 26 Feb 2019 17:39:51 INFO yzfbrowser.py:18[Quit()] Quit() exit browser
Tue, 26 Feb 2019 17:42:04 INFO hebei.py:24[<module>()] Hebei starts
Tue, 26 Feb 2019 17:42:04 INFO yzftaxbot.py:655[register_login_task()] 
Tue, 26 Feb 2019 17:42:04 INFO yzftaxbot.py:695[run()] 第1次运行登录函数
Tue, 26 Feb 2019 17:42:13 INFO yzftaxbot.py:719[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Tue, 26 Feb 2019 17:42:13 ERROR yzftaxbot.py:725[run()] Message: unknown error: Runtime.evaluate threw exception: SyntaxError: missing ) after argument list
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 722, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 11, in main
    YzfBrowser.execute_script("alert(test js )")
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.evaluate threw exception: SyntaxError: missing ) after argument list
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 17:42:13 ERROR hebei.py:30[<module>()] Message: unknown error: Runtime.evaluate threw exception: SyntaxError: missing ) after argument list
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 26, in <module>
    main()
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 19, in main
    MyBot.run()
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 727, in run
    raise e  # TODO 重试次数用完，设置Task
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 722, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 11, in main
    YzfBrowser.execute_script("alert(test js )")
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.evaluate threw exception: SyntaxError: missing ) after argument list
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Tue, 26 Feb 2019 17:42:13 INFO yzfbrowser.py:18[Quit()] Quit() exit browser
Thu, 28 Feb 2019 11:04:31 INFO hebei.py:24[<module>()] Hebei starts
Thu, 28 Feb 2019 11:04:31 INFO yzftaxbot.py:646[register_login_task()] 
Thu, 28 Feb 2019 11:04:31 INFO yzftaxbot.py:686[run()] 第1次运行登录函数
Thu, 28 Feb 2019 11:04:38 INFO yzftaxbot.py:710[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Thu, 28 Feb 2019 11:04:52 ERROR yzftaxbot.py:716[run()] Message: unknown error: Runtime.evaluate threw exception: SyntaxError: missing ) after argument list
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 713, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 11, in main
    YzfBrowser.execute_script("alert(test js )")
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.evaluate threw exception: SyntaxError: missing ) after argument list
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

Thu, 28 Feb 2019 13:53:50 INFO hebei.py:25[<module>()] Hebei starts
Thu, 28 Feb 2019 13:53:50 INFO yzftaxbot.py:646[register_login_task()] 
Thu, 28 Feb 2019 13:53:50 INFO yzftaxbot.py:686[run()] 第1次运行登录函数
Thu, 28 Feb 2019 13:54:04 INFO hebei.py:25[<module>()] Hebei starts
Thu, 28 Feb 2019 13:54:04 INFO yzftaxbot.py:646[register_login_task()] 
Thu, 28 Feb 2019 13:54:04 INFO yzftaxbot.py:686[run()] 第1次运行登录函数
Thu, 28 Feb 2019 13:54:12 INFO yzftaxbot.py:710[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Thu, 28 Feb 2019 13:55:14 ERROR hebei.py:31[<module>()] 任务typeCJ不支持任务ID:HBGS_SZRD
Traceback (most recent call last):
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 27, in <module>
    main()
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 20, in main
    MyBot.run()
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 703, in run
    raise Exception("任务type" + task_group.type() + "不支持任务ID:" + task_group.id())
Exception: 任务typeCJ不支持任务ID:HBGS_SZRD
Thu, 28 Feb 2019 13:55:20 INFO yzfbrowser.py:19[Quit()] Quit() exit browser
Thu, 28 Feb 2019 13:58:47 INFO hebei.py:26[<module>()] Hebei starts
Thu, 28 Feb 2019 13:58:47 INFO yzftaxbot.py:646[register_login_task()] 
Thu, 28 Feb 2019 13:58:47 INFO yzftaxbot.py:686[run()] 第1次运行登录函数
Thu, 28 Feb 2019 13:58:54 INFO yzftaxbot.py:710[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Thu, 28 Feb 2019 13:59:28 INFO yzftaxbot.py:710[run()] 第1次执行任务（任务type=CJ, 任务id=HBGS_SZRD）
Thu, 28 Feb 2019 14:22:07 INFO hebei.py:26[<module>()] Hebei starts
Thu, 28 Feb 2019 14:22:07 INFO yzftaxbot.py:646[register_login_task()] 
Thu, 28 Feb 2019 14:22:07 INFO yzftaxbot.py:686[run()] 第1次运行登录函数
Thu, 28 Feb 2019 14:22:15 INFO yzftaxbot.py:710[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Thu, 28 Feb 2019 14:22:27 INFO yzftaxbot.py:710[run()] 第1次执行任务（任务type=CJ, 任务id=HBGS_SZRD）
Fri, 01 Mar 2019 09:55:57 INFO hebei.py:26[<module>()] Hebei starts
Fri, 01 Mar 2019 09:55:57 INFO yzftaxbot.py:646[register_login_task()] 
Fri, 01 Mar 2019 09:55:57 INFO yzftaxbot.py:686[run()] 第1次运行登录函数
Fri, 01 Mar 2019 09:56:05 INFO yzftaxbot.py:710[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Fri, 01 Mar 2019 09:56:41 ERROR yzftaxbot.py:716[run()] 没有找到元素#app > div > div > section > div > section > div > div > div.ant-tabs-content > span > div:nth-child(2) > div > div > div > div > table
Traceback (most recent call last):
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 713, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 15, in main
    table = read_tbody("#app > div > div > section > div > section > div > div > div.ant-tabs-content > span > div:nth-child(2) > div > div > div > div > table")
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 915, in read_tbody
    raise Exception("没有找到元素" + tbody_selector_str)
Exception: 没有找到元素#app > div > div > section > div > section > div > div > div.ant-tabs-content > span > div:nth-child(2) > div > div > div > div > table
Fri, 01 Mar 2019 09:58:14 INFO hebei.py:26[<module>()] Hebei starts
Fri, 01 Mar 2019 09:58:14 INFO yzftaxbot.py:646[register_login_task()] 
Fri, 01 Mar 2019 09:58:14 INFO yzftaxbot.py:686[run()] 第1次运行登录函数
Fri, 01 Mar 2019 09:58:34 ERROR yzftaxbot.py:692[run()] 'NoneType' object has no attribute 'is_displayed'
Traceback (most recent call last):
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 688, in run
    self.LoginTaskFunc()
  File "D:\InterfaceSystem\RPA\hebei\tasks\login.py", line 49, in main
    WebDriverWait(YzfBrowser, 30).until(EC.element_to_be_clickable((By.ID, "companyEnter")))
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 297, in __call__
    element = visibility_of_element_located(self.locator)(driver)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 148, in _element_if_visible
    return element if element.is_displayed() == visibility else False
AttributeError: 'NoneType' object has no attribute 'is_displayed'
Fri, 01 Mar 2019 09:58:34 ERROR hebei.py:32[<module>()] 'NoneType' object has no attribute 'is_displayed'
Traceback (most recent call last):
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 28, in <module>
    main()
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 21, in main
    MyBot.run()
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 694, in run
    raise e  # 重试次数用完，向外层抛异常
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 688, in run
    self.LoginTaskFunc()
  File "D:\InterfaceSystem\RPA\hebei\tasks\login.py", line 49, in main
    WebDriverWait(YzfBrowser, 30).until(EC.element_to_be_clickable((By.ID, "companyEnter")))
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 297, in __call__
    element = visibility_of_element_located(self.locator)(driver)
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "C:\Users\PC\PycharmProjects\untitled\venv\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 148, in _element_if_visible
    return element if element.is_displayed() == visibility else False
AttributeError: 'NoneType' object has no attribute 'is_displayed'
Fri, 01 Mar 2019 09:58:34 INFO yzfbrowser.py:19[Quit()] Quit() exit browser
Fri, 01 Mar 2019 09:58:45 INFO hebei.py:26[<module>()] Hebei starts
Fri, 01 Mar 2019 09:58:45 INFO yzftaxbot.py:646[register_login_task()] 
Fri, 01 Mar 2019 09:58:45 INFO yzftaxbot.py:686[run()] 第1次运行登录函数
Fri, 01 Mar 2019 09:58:53 INFO yzftaxbot.py:710[run()] 第1次执行任务（任务type=CJ, 任务id=HB_BASE_INFO）
Fri, 01 Mar 2019 09:59:35 ERROR yzftaxbot.py:716[run()] 没有找到元素#app > div > div > section > div > section > div > div > div.ant-tabs-content > span > div:nth-child(2) > div > div > div > div > table > tbody
Traceback (most recent call last):
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 713, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 15, in main
    table = read_tbody("#app > div > div > section > div > section > div > div > div.ant-tabs-content > span > div:nth-child(2) > div > div > div > div > table > tbody")
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 915, in read_tbody
    raise Exception("没有找到元素" + tbody_selector_str)
Exception: 没有找到元素#app > div > div > section > div > section > div > div > div.ant-tabs-content > span > div:nth-child(2) > div > div > div > div > table > tbody
Fri, 01 Mar 2019 09:59:38 ERROR hebei.py:32[<module>()] 没有找到元素#app > div > div > section > div > section > div > div > div.ant-tabs-content > span > div:nth-child(2) > div > div > div > div > table > tbody
Traceback (most recent call last):
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 28, in <module>
    main()
  File "D:/InterfaceSystem/RPA/hebei/hebei.py", line 21, in main
    MyBot.run()
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 718, in run
    raise e  # TODO 重试次数用完，设置Task
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 713, in run
    self.TaskFuncMap[task_group.type()][task_group.id()]()
  File "D:\InterfaceSystem\RPA\hebei\tasks\cj_base_info.py", line 15, in main
    table = read_tbody("#app > div > div > section > div > section > div > div > div.ant-tabs-content > span > div:nth-child(2) > div > div > div > div > table > tbody")
  File "D:\InterfaceSystem\RPA\yzfwebbase\yzftaxbot.py", line 915, in read_tbody
    raise Exception("没有找到元素" + tbody_selector_str)
Exception: 没有找到元素#app > div > div > section > div > section > div > div > div.ant-tabs-content > span > div:nth-child(2) > div > div > div > div > table > tbody
